### ISSUE TITLE
[슬라이드 준비] For introduction and conclusion

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-presentation-team2#10]
@elmisty elevator pitch를 위한 슬라이드 이외에도 conclusion 슬라이드도 함께 준비해서 PR 보내주시기 바랍니다. 저도 introduction 슬라이드를 함께 준비하겠습니다.

**Comment by elmisty** [comment]
확인했습니다. 수요일 전에 초본 커밋하겠습니다.

**Comment by leeswimming** [comment]
Since all slides for the introduction and the conclusion are merged to the master branch, I close this issue.
