### ISSUE TITLE
[PT Rehearsal & Review] Presentation Rehearsal

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-presentation-team2#11]
발표 리허설을 위해 금요일에 모이려고 하는데 시간 안되시는 분 있으시면 커멘트 남겨주시기 바랍니다.

**Comment by Hexife** [comment]
금요일 5시 전에만 진행되면 괜찮을 듯 합니다.

**Comment by elmisty** [comment]
금요일 13~15시, 17:30~ 제외하고 다 가능합니다.

**Comment by Hexife** [comment]
그럼 금요일 아침에 하는 것도 좋아 보입니다.

**Comment by hongsh93** [comment]
3-5는 어떤가요? 아침에 약해서... 그때 시간 안되시면 그냥 아침에 해도 괜찮습니다

**Comment by leeswimming** [comment]
금요일 15시에 N5 2243호에서 모이도록 하겠습니다.

**Comment by leeswimming** [comment]
Since we already had a rehearsal twice, I close this issue.
