### ISSUE TITLE
[TA] Comments from professor/TAs

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-presentation-team2#33]
안녕하세요 :) 조교 김수민입니다.

이번 과제 하시느라 다들 수고 많으셨습니다.
이번 과제를 통해 github의 milestone과 issue를 이용한 협업에 익숙해지셨나요?
아래는 지난 발표를 보고 교수님과 조교들이 평가하면서 남긴 코멘트들입니다.
Feedback으로 삼으시면 좋을 것 같습니다

- 시작은 좋음.
- 슬라이드 일관성 좋았음.
- 결론 슬라이드에서의 그림(에니메이션)이 무엇을 의미하는지 전혀 알수 없음
- 팀소개가 재밌었음
- 시작이 매끄러웠음 평범했음
- 팀 소개부분을 재밌게 잘 하였음
- 개인소개 부분에서는 전반적으로, 팀 소개때 보여준 위트있는 모습이 안나타나서 아쉬움
- 발표시간 준수 필요
- 발표준비가 다소 덜 된 느낌
- intro 부분이 재밌었음
- 발표 준비가 좀 더 필요해 보였음
- 전체적으로 그림의 크기가 좀 더 크면 좋았을 듯
- Good Introduction
- Have same format
- 팀 소개가 재미있음
- 택진씨만 주어진 시간을 넘겼지만, 팀 발표였기 때문에 다 같이 연습을 더 해서 시간을 맞추었으면 하는 아쉬움이 남습니다.
- 흥미로운 intro와 일관성 있는 구성

아래는 개인별 comment입니다.
- 이수영
  * 수영리 슬라이드는 0.1초만에 지나감. 이해하기 쉬운 좋은 발표였음. 사람들이 기억하기 쉬운 swimming이라는 단어를 계속해서 강조하는 것 역시 매우 훌륭했음.
  * 이름을 swimming과 연관지어 설명하여 기억에 잘 남음. 듣기 편한 톤과 빠르기로 발표를 진행해서 좋았음
  * 이수영씨의 소개중에, "자신을 기억해달라"라는 말이 기억에 남음
- 이택진
  * 피들러 설명에서 무슨 말인지 이상했음. 닉네임에 대한 의미는? 닉네임에 대해서 그냥 그렇다고만 말하고 그 의미나 이유에 대해서 설명하지 않음.
  * 피들러를 설명할 때 망설이는 간격이 길어서 발표 준비가 잘 되지 않았다는 인상을 받음
  * Time keeping을 잘 했으면 좋겠습니다, 뜸들이는 부분을 줄이는 것이 중요.
- 홍승한
  * 그림이 지도교수가 쓰는 그림과 같음. 본인이 그린것인가? citation은? 아톰에 대한 자랑인지 자신의 환경에 관한 자랑인지 모르겠음.
  * 많지 않은 내용을 길게 설명하여 지루한 느낌을 받음
- 문석주
  * 발표를 한다기 보다 글을 읽었음. 두 개의 에디터를 쓴다는데 어떨때 뭘 쓰는지?
  * 스크립트를 읽는다는 느낌을 받음

앞으로 쭉 화이팅 하시기 바랍니다!

조교 김수민 드림

=====

3.14 추가)
프레젠테이션에 걸린 시간은 다음과 같습니다:
이수영: 2분 35초
이택진: 3분 23초
홍승한: 2분 37초
문석주: 2분 21초
Total : 12분 40초

**Comment by sangkilc** [comment]
@soomin-kim  Thank you for creating this issue. I think you'd better put the presentation time for each member in your summary.

**Comment by soomin-kim** [comment]
@sangkilc Your suggestion has got accepted :)
