### ISSUE TITLE
[PGP Key 활용] PGP Key 활용 데모

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-presentation-team2#35]
PGP Key를 활용하여 암호화된 메시지를 Slack으로 주고 받을 예정입니다.
상대방의 키로 메시지를 암호화하고 본인의 키로 메시지를 복호화하는 방법을 토요일까지 익혀두시기 바랍니다.
궁금한 점은 comment로 남겨주세요

**Comment by Hexife** [comment]
Slack 말고 그냥 이메일로 하는게 어때?
Slack은 이미 https 통신이라 암호화 2중으로 하는 모양이라 효율적인 이용은 아닌거 같아서..

평가 항목에 Did students use PGP keys effectively? 라고 써있는거 봐서 적절히는 사용해야 할거 같음

**Comment by leeswimming** [comment]
넵 그렇게 하도록 하죠

**Comment by leeswimming** [comment]
Since we have finished the demo and added slides for it, I close this issue. #43
