### ISSUE TITLE
[TA help wanted] Commit sign 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by hongsh93** [KAIST-IS521/2018s-presentation-team2#53]
저는 숙제를 window에서 진행중이고요
git commit -S -m "메시지"를 입력하기 위해 
git config --global user.signingkey 제키 를 해도 사항상 secret key가 available 하지 않다는 메시지만 뜹니다.
![2018-03-18 22 46 05](https://user-images.githubusercontent.com/22565656/37568112-f6cf3914-2b13-11e8-8848-aa0544a50d78.PNG)
![2018-03-18 23 53 58](https://user-images.githubusercontent.com/22565656/37568131-5772c7ae-2b14-11e8-84b0-542f75a3f658.PNG)
![2018-03-19 01 25 47](https://user-images.githubusercontent.com/22565656/37568141-78b03f28-2b14-11e8-813e-4019532d4541.PNG)

제 키 입력창에 저 키가 아닌가해서 finger print와 깃에 입력된 key ID를 모두 입력해보았는데 안되는건 마찬가지 였습니다.

그래서 이 오류를 해결하기 위해 여러 사이트를 참고했지만 
http://blog.naver.com/PostView.nhn?blogId=opusk&logNo=220986282252&parentCategoryNo=&categoryNo=16&viewDate=&isShowPopularPosts=false&from=postView

http://sunphiz.me/wp/archives/1663

http://sunphiz.me/wp/archives/1654

https://git-scm.com/book/ko/v2/Git-%EB%8F%84%EA%B5%AC-%EB%82%B4-%EC%9E%91%EC%97%85%EC%97%90-%EC%84%9C%EB%AA%85%ED%95%98%EA%B8%B0

제 오류는 전혀 해결되지 않아서 질문드립니다.
제 secret key는 잘보관되어 있으며 다른 학생들의 key에 sign도 여러번 했지만 깃에 사인할때는 계속 오류가 뜹니다.

**Comment by soomin-kim** [comment]
제가 Windows 환경에서 gpg랑 git을 같이 써보지 않아서 잘 모르겠지만,
https://stackoverflow.com/questions/36810467/git-commit-signing-failed-secret-key-not-available
여기에 있는 방법들도 혹시 시도해보셨나요?

**Comment by Hexife** [comment]
저희가 해결을 시도할 때 윈도우 환경변수 설정을 제외한 나머지는 다 시도 했었습니다.

@hongsh93 환경변수 설정 한번 해보시고 다시 시도해 보는게 좋아 보입니다.
