### ISSUE TITLE
[TA] Comment from Professor for activity 3

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-presentation-team2#54]
안녕하세요, 조교 김수민입니다.

Activity 3 presentation에 대한 교수님의 comment입니다.
Feedback으로 사용하시면 좋을 것 같습니다.

- Title에서 YOUNG ME, PGP 라고 하면 뭘 말하려는 건지 모르겠음. 예를 들면:
  Team 'Young ME', IS-521 PGP Activity. 정도로 써준다면 더 좋을 듯.
- GPG encryption을 하는데 sudo를 쓰는 이유는?
- 마지막 5-6 슬라이드에서는 오로지 we love PGP라는 얘기만 하고 있을 뿐 그에 대한
  확실한 이유나 근거가 제시되지 않음. 단순히 안전한 메시지를 보낼수 있다에서
  그침. 좀 더 다양한 PGP사용의 방법에 대해서 조사해봤으면 하는 아쉬움이 남음.

그리고 제가 issue로 남긴 comment들은 적당한 때가 되었다고 생각하시면 close하셔도 됩니다. :)

조교 김수민 드림

**Comment by Hexife** [comment]
GPG encryption을 하는데 sudo를 쓰는 이유는?
-> Ubuntu 17.10에서 gpg 세팅을 하니 gpg 관련 디렉터리(.gnupg 등)의 소유권이 root로 생성 되었습니다. 소유자를 바꾸고 쓰다보니 gpg나 git 둘 중 하나를 사용시에 gpg에서 소유자 관련 warning을 확인하여 그냥 root로 사용하였습니다. 
( 그런데 지금은 재현이 안되는 것을 봐서 제가 잘못 본 것 일수도 있습니다....)

일반 계정 권한으로 사용해도 문제가 되지 않는 것을 확인하게 되면 일반 계정으로 사용하겠습니다.
