### ISSUE TITLE
[슬라이드 준비] For individuals

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-presentation-team2#9]
3분씩 주어질 elevator pitch를 위한 슬라이드를 목요일까지 본인의 branch에서 작업해서 PR을 보내면 제가 확인하고 merge 하겠습니다.

**Comment by leeswimming** [comment]
슬라이드 작성하실 때 [Activity Overview & Grading Criteria](https://github.com/KAIST-IS521/2018-Spring/blob/master/Activities/0228.md)  꼭 참고 하세요

**Comment by Hexife** [comment]
슬라이드를 각자의 PITCHME.md 파일로 나눠서 메인 PITCHME.md 파일에 합치는건 어떤가요?

ex>
./PITCHME.md                  // Main, 각자의 PITCHME.md를 여기다 Include
ㄴ/hexife/PITCHME.md    // hexife의 PITCHME.md
ㄴ/leeswimming/PITCHME.md // leeswimming의 PITCHME.md
.
.

**Comment by leeswimming** [comment]
파일을 나누어서 작성하고 한 명이 그걸 합치자는 말씀이신가요?

**Comment by elmisty** [comment]
지금처럼 Branch로 유지하자는거 아닐까..?

**Comment by Hexife** [comment]
놉놉 pitchme에도 php include하는것과 유사하게 할수 있더라구요
(리더 수영님은 js의 load 생각하시면 될듯!)

**Comment by leeswimming** [comment]
아 그런 의미군요. 이해했습니다. 제 개인적인 생각에는 git을 통한 collaboration을 경험한다는 수업의 취지를 생각했을 때 같은 파일을 여려 사람이 각자 branch에서 편집하고 conflict가 발생하면 resolve 하는 게 좋을 것 같다고 생각하는데 다른 분들 의견을 어떠신가요?

**Comment by Hexife** [comment]
꼭 하자는 말은 아니었긴 한데,
Conflict 해결은 전 activity에서 이미 경험하고 해결 해본 사람도 있을테고, Collaboration에서 conflict가 덜 나도록 프로젝트 구조를 조정하는것도 좋은 방향이라고 생각합니다.

**Comment by leeswimming** [comment]
네 그것도 일리 있는 이야기라고 생각합니다. 저는 어느 쪽이든 상관없습니다. 팀원들에게 편한 방향으로 진행하면 될 것 같습니다. 다른 분들 의견도 들려주세요.

**Comment by elmisty** [comment]
저도 수업의 취지를 생각해봤을때 수영님의 의견이 더 맞다고 생각합니다. 이번 기회에 체험해보는게 어떨까 싶네

**Comment by Hexife** [comment]
수업의 취지중에 Collaboration 상황에서 발생한 Conflict 해결하는 것도 있을 수 있지만 굳이 줄일 수 있는데 체험하기 위해 그대로 간다는 것에는 동의할 수 없습니다. 

여러명이 Collaboration하는 상황에서의 Conflict와 그렇지 않은 상황에서의 Conflict의 차이는 Conflict가 발생한
 코드 작성자 끼리 이야기로 조정한 후에 해결하는 것 밖에 없다고 생각하는 것도 그 이유 중 하나이고,
논의를 하면서 더 효율적인 구조를 찾아 적용하는 방향이 오히려 수업의 취지에 맞지 않나 싶네요.

**Comment by leeswimming** [comment]
제가 오해의 소지가 있게 커멘트를 남겼네요.
제 의도는 branch를 만들어서 git을 잘 사용한다면 같은 파일을 여러 branch에서 수정하더라도 자동으로 merge가 되고 conflict가 나는 일이 드무니까 실수로 conflict가 발생하는 경우에는 resolve를 하면 된다는 것으로 제가 앞서 이야기한 경험이란 conflict가 발생하지 않게 각자 브랜치에서 git을 잘 사용하는 것이었습니다. (conflict를 경험하자는 의미가 아닙니다.)
또한 ```PITCHME.md```의 경우에는 작성해야 할 양이 많지 않아서 conflict가 발생할 가능성이 적다고 생각해서 오히려 @Hexife가 말씀하신 것처럼 파일을 나누는 게 더 일을 추가하는 거라고 생각했습니다.

**Comment by leeswimming** [comment]
Since all slides are merged to the master branch, I close this issue
